#! /usr/bin/env bash

# Physical path for a .app bundle (follows symlinks).
_nonbrew_apps_phys_path() {
    (cd -P "$1" 2>/dev/null && pwd -P)
}

# Returns 0 if the resolved path lives under Homebrew Caskroom or Cellar.
_nonbrew_apps_is_brew_managed() {
    case "$1" in
        */Caskroom/* | */Cellar/*) return 0 ;;
        *) return 1 ;;
    esac
}

# Prints paths of .app bundles in /Applications and ~/Applications that are not
# com.apple.* (by bundle id) and do not resolve under Caskroom/Cellar.
list_nonbrew_applications() {
    local app bid phys roots=()
    [[ -d /Applications ]] && roots+=(/Applications)
    [[ -d "$HOME/Applications" ]] && roots+=("$HOME/Applications")
    ((${#roots[@]})) || return 0
    find "${roots[@]}" \( -path '*.app/*' -prune \) -o -type d -name '*.app' -print0 2>/dev/null \
        | while IFS= read -r -d '' app; do
            local plist="$app/Contents/Info.plist"
            bid=""
            if [[ -f "$plist" ]]; then
                bid=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$plist" 2>/dev/null) || bid=""
            fi
            [[ "$bid" == com.apple.* ]] && continue
            phys=$(_nonbrew_apps_phys_path "$app") || continue
            if _nonbrew_apps_is_brew_managed "$phys"; then
                continue
            fi
            printf '%s\n' "$app"
        done | LC_ALL=C sort -f
}

# Writes backup/nonbrew-applications.txt (header + list_nonbrew_applications).
record_nonbrew_applications() {
    local out="${1:?record_nonbrew_applications: output path required}"
    {
        echo "# Generated by backup.sh — apps under /Applications and ~/Applications"
        echo "# that are not resolved under Homebrew Caskroom/Cellar and are not com.apple.*"
        echo "# (best-effort; manual installers and odd casks may be misclassified)"
        echo ""
        list_nonbrew_applications || true
    } >"$out"
}

# After restore: print the saved list if present.
show_nonbrew_applications() {
    local f="${1:-$BACKUP_DIR/nonbrew-applications.txt}"
    if [[ -f "$f" ]]; then
        echo ""
        echo -e "${ARROW}Applications not installed via Homebrew (from last backup; install manually if needed):"
        cat "$f"
        echo ""
    fi
}
